# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2096d4807744f04dd996e2909e71baaa2778aafb7340fa4e16b096013f1cd810f420caef1ecb99d42bf3fb37e6da8338d9007b78ba02500d4939cba07187c1f1

test:
  secret_key_base: b356d3091e4546abf07393e353030a6513711877d43bd43aef82c07f3094943fd7b78499100d0440ff7768aa8cc1de3b9549ce3dd3fdfa5bca4bbf56bf0a55a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
